version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: backtest
      POSTGRES_USER: backtest
      POSTGRES_PASSWORD: backtest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://backtest:backtest@db:5432/backtest
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to start...' &&
        while ! pg_isready -h db -p 5432 -U backtest; do
          sleep 1;
        done &&
        alembic upgrade head &&
        python scripts/import_prices.py &&
        python scripts/run_backtest.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
