"""Add backtest model

Revision ID: 90ad1f6e13f4
Revises: 210d87aaeb8c
Create Date: 2025-03-09 13:24:09.034674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ad1f6e13f4'
down_revision: Union[str, None] = '210d87aaeb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'price',
               existing_type=sa.NUMERIC(precision=13, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=13, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
